# -*- coding: utf-8 -*-
"""TASK 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOHvA3honRaUTKhdTAoqn1KHkVUYOVYz
"""

# Commented out IPython magic to ensure Python compatibility.
import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display plots in the notebook
# %matplotlib inline
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]       # Get the actual filename
df = pd.read_csv(io.BytesIO(uploaded[filename]))

df.head()
df.shape           # Check rows and columns
df.info()          # Data types and null values
df.describe()      # Summary statistics
df.columns         # List all column names
# Check for missing values
df.isnull().sum()

# Drop duplicates if any
df.drop_duplicates(inplace=True)

# Fill missing values if needed
df.fillna(0, inplace=True)

# Remove leading/trailing spaces and quotes from column names
df.columns = df.columns.str.strip().str.replace('"', '')
df.columns
sns.histplot(df['Height(Inches)'], kde=True)
plt.title("Height Distribution")
plt.show()

sns.histplot(df['Weight(Pounds)'], kde=True)
plt.title("Weight Distribution")
plt.show()
df.describe()